### PR TITLE
Add personas markdown doc

### PR DESCRIPTION
**Pull request by hemajv**
Adding a markdown document to list all the personas identified in https://github.com/AICoE/data-driven-development/issues/22 for project meteor

### CODE REVIEW

**Review by harshad16 — COMMENTED** [review]
/lgtm
thanks @hemajv  for putting this together :+1:

**Review by aakankshaduggal — APPROVED** [review]
/lgtm :ship:

**Review by pacospace — APPROVED** [review]
lgtm!!! 💯 👏🏼

**Review by isabelizimm — APPROVED** [review]
lgtm!

**Review by tumido — APPROVED** [review]
/lgtm
/approve

**Comment by tumido** [comment]
Seems tide is not enabled here. Fixing https://github.com/thoth-station/thoth-application/pull/1821

**Pull request merged**
