### PR TITLE
Add metrics doc

### PR DESCRIPTION
**Pull request by hemajv**
Adding an initial metrics markdown to document all the metrics we would like to collect.

Reference: https://docs.google.com/document/d/1SWv29LkjKUA4rkM3V6bR6GzVWJPWMgHm-RUPH7xiPrE/edit?usp=sharing
Related issue: https://github.com/AICoE/data-driven-development/issues/21

_Note_: This document is likely to be iterated upon and updated over time and this first version is for us to have a good starting point.

### CODE REVIEW

**Comment by hemajv** [comment]
/hold
until #39 is merged

**Review by tumido — COMMENTED** [review]
/lgtm :+1:

**Review by isabelizimm — APPROVED** [review]
looks good!

**Review by aakankshaduggal — COMMENTED** [review]
/lgtm

**Review by tumido — APPROVED** [review]
/approve

**Pull request merged**
